// feature-video.js
// "Follow the cursor" feature tour over real captured screenshots
// (assets/tour/*.webp + frames.js, generated by scripts/capture-tour.mjs).

(function () {
  const MOVE_MS = 620;
  const FRAME_W = 340;
  const STAGE_MAX_H = 292;

  const TIMELINE = [
    { frame: 'idle', hold: 3400, caption: 'This is the popup. Open it on any job posting — one page controls everything.' },
    { frame: 'idle', move: 'generate', click: true, hold: 3400, caption: 'Visit a job posting, then click Generate PDF Resume.' },
    { frame: 'generating', move: 'genLabel', hold: 3600, badge: 'dont', caption: 'While the popup glows blue: do not close the popup and do not re-click Generate. Blue = work in progress.' },
    { frame: 'success', move: 'genLabel', hold: 3200, badge: 'do', caption: 'Blue → green means done: the resume (and cover letter) PDFs are already downloaded.' },
    { frame: 'styleOpen', move: 'faangOption', click: true, hold: 2800, caption: 'Four PDF layouts — Professional, FAANG, Double Sided, Academic CV. Prompt tuning follows your pick.' },
    { frame: 'styleFaang', move: 'styleTrigger', hold: 2200, caption: 'Your choice saves instantly for all future generations.' },
    { frame: 'coverLetterOn', move: 'coverToggle', hold: 2600, caption: 'One toggle adds a tailored cover letter to every run — tone adapts to your style.' },
    { frame: 'fillFilling', move: 'fillBtn', hold: 2600, badge: 'dont', caption: "Fill Form completes application forms. Amber glow = working. Don't type into fields while it fills." },
    { frame: 'fillSuccess', move: 'fillBtn', hold: 2600, badge: 'do', caption: 'Green = done, safe to edit. Name, contact, work-auth, salary: free from your saved profile. It never submits.' },
    { frame: 'setupComplete', move: 'watchBtn', hold: 2600, caption: 'After setup you get this tour offered once — and the ▶ header button replays it anytime.' },
    { frame: 'refineAts', move: 'refineBtn', hold: 2600, caption: 'Refine Resume asks up to 5 gap questions, then rewrites your resume. Check ATS scores on demand.' },
    { frame: 'atsResult', hold: 3000, caption: 'The ring shows the before → after score, with every critical issue and its fix.' },
    { frame: 'appProfile', move: 'autofillBtn', hold: 2400, caption: 'Answer common application questions once — Auto-fill pulls answers straight from your resume.' },
    { frame: 'trackerBoard', hold: 3200, caption: 'Every Generate auto-saves the job to the Job Tracker — company, role, recruiter, notes. Full loop, done.' }
  ];

  const FRAMES = {};
  const BADGES = {
    dont: { label: "DON'T", cls: 'fvb-dont' },
    do: { label: 'DO', cls: 'fvb-do' },
  };
  const HOME = { x: 0.5, y: 0.06 };

  let modal = null;
  let stage = null;
  let frameA = null;
  let frameB = null;
  let captionEl = null;
  let badgeEl = null;
  let playBtn = null;
  let progressFill = null;
  let dotsWrap = null;
  let countEl = null;
  let cursorEl = null;
  let typingChip = null;

  let activeImg = null;
  let stepIndex = 0;
  let playing = false;
  let built = false;
  let stepTimer = null;
  let typingTimer = null;
  let typingDoneTimer = null;
  let rippleTimer = null;
  let moveRaf = null;
  let stepStart = 0;
  let pausedElapsed = 0;
  let cursorPt = { x: 0, y: 0 };

  const playSvg = '<svg width="12" height="12" viewBox="0 0 24 24" fill="currentColor" aria-hidden="true"><path d="M8 5v14l11-7z"/></svg>';
  const pauseSvg = '<svg width="12" height="12" viewBox="0 0 24 24" fill="currentColor" aria-hidden="true"><path d="M6 4h4v16H6z"/><path d="M14 4h4v16h-4z"/></svg>';

  function ensureBuilt() {
    if (built) return;
    modal = document.createElement('div');
    modal.id = 'featureVideoModal';
    modal.className = 'fv-modal';
    modal.style.display = 'none';
    modal.innerHTML = `
      <div class="fv-backdrop"></div>
      <div class="fv-card" role="dialog" aria-modal="true" aria-label="PocketResume feature tour">
        <div class="fv-head">
          <span class="fv-title" id="fvTitle">Feature tour</span>
          <button type="button" class="fv-close" id="fvCloseBtn" aria-label="Close feature tour">✕</button>
        </div>
        <div class="fv-stage" id="fvStage">
          <img id="fvFrameA" class="fv-frame active" alt="" draggable="false">
          <img id="fvFrameB" class="fv-frame" alt="" draggable="false">
          <div class="fv-badge" id="fvBadge" style="display:none;"></div>
        </div>
        <p class="fv-caption" id="fvCaption"></p>
        <div class="fv-progress-track"><div class="fv-progress-fill" id="fvProgress"></div></div>
        <div class="fv-controls">
          <button type="button" class="fv-play" id="fvPlayBtn" aria-label="Play or pause tour"></button>
          <div class="fv-dots" id="fvDots"></div>
          <span class="fv-count" id="fvCount"></span>
        </div>
      </div>`;
    document.body.appendChild(modal);
    stage = modal.querySelector('#fvStage');
    frameA = modal.querySelector('#fvFrameA');
    frameB = modal.querySelector('#fvFrameB');
    captionEl = modal.querySelector('#fvCaption');
    badgeEl = modal.querySelector('#fvBadge');
    playBtn = modal.querySelector('#fvPlayBtn');
    progressFill = modal.querySelector('#fvProgress');
    dotsWrap = modal.querySelector('#fvDots');
    countEl = modal.querySelector('#fvCount');

    TIMELINE.forEach((step, i) => {
      const dot = document.createElement('button');
      dot.type = 'button';
      dot.className = 'fv-dot';
      dot.title = `Step ${i + 1} of ${TIMELINE.length}`;
      dot.addEventListener('click', () => jumpToStep(i));
      dotsWrap.appendChild(dot);
    });

    const assets = window.PocketResumeTourAssets;
    if (!assets || !assets.frames || !assets.frames.length) {
      captionEl.textContent = 'Tour frames missing — run npm run build:tour.';
    }
    (assets ? assets.frames : []).forEach((f) => {
      const img = new Image();
      img.src = (assets.dir || 'assets/tour/') + f.file;
      FRAMES[f.id] = { img, hotspots: f.hotspots || {}, clipH: f.clipH || assets.clipH || 228 };
    });

    playBtn.innerHTML = playSvg;
    playBtn.addEventListener('click', togglePlay);
    modal.querySelector('.fv-backdrop').addEventListener('click', close);
    modal.querySelector('#fvCloseBtn').addEventListener('click', close);
    document.addEventListener('keydown', onKeydown);

    cursorEl = document.createElement('div');
    cursorEl.className = 'fv-pointer';
    cursorEl.style.opacity = '0';
    cursorEl.innerHTML = `
      <svg width="27" height="27" viewBox="0 0 28 28" aria-hidden="true">
        <path d="M4.5 2l16.4 14.8-7.3 1 4.3 9.4-4.2 1.9-4.3-9.4-6.2 5.2z" fill="#ffffff" stroke="#151515" stroke-width="1.5" stroke-linejoin="round"/>
      </svg>
      <span class="fv-pointer-ring"></span>`;
    activeImg = frameA;
    stage.appendChild(cursorEl);
    built = true;
  }

  function onKeydown(e) {
    if (!modal || modal.style.display === 'none') return;
    if (e.key === 'Escape') { close(); return; }
    if (e.key === ' ') { e.preventDefault(); togglePlay(); }
  }

  function timersClear() {
    if (stepTimer) { clearTimeout(stepTimer); stepTimer = null; }
    if (typingTimer) { clearInterval(typingTimer); typingTimer = null; }
    if (typingDoneTimer) { clearTimeout(typingDoneTimer); typingDoneTimer = null; }
    if (rippleTimer) { clearTimeout(rippleTimer); rippleTimer = null; }
    if (moveRaf) { cancelAnimationFrame(moveRaf); moveRaf = null; }
    removeTypingChip();
  }

  function totalsFor(step) {
    return MOVE_MS + (step.hold || 2000);
  }

  function setProgress(fraction) {
    progressFill.style.width = `${Math.max(0, Math.min(100, fraction * 100))}%`;
  }

  function pauseStep() {
    pausedElapsed = elapsedWhenStopped();
    timersClear();
    const step = TIMELINE[stepIndex];
    if (step) setProgress(pausedElapsed / totalsFor(step));
  }

  function elapsedWhenStopped() {
    const step = TIMELINE[stepIndex];
    if (!step) return 0;
    if (stepStart) return Math.min(totalsFor(step), Date.now() - stepStart);
    return Math.min(totalsFor(step), pausedElapsed);
  }

  function hotspotXY(step) {
    if (!stage) return { x: 0, y: 0 };
    const asset = FRAMES[step.frame];
    const w = stage.clientWidth;
    const ratio = asset ? asset.clipH / FRAME_W : 228 / FRAME_W;
    const imgH = Math.min(STAGE_MAX_H, w * ratio);
    const imgW = imgH / ratio;
    const offX = (w - imgW) / 2;
    let nx = HOME.x;
    let ny = HOME.y;
    if (step.move !== undefined && asset) {
      const spot = asset.hotspots[step.move] || [0.5, 0.5];
      nx = spot[0];
      ny = spot[1];
    }
    return { x: offX + nx * imgW, y: ny * imgH };
  }

  function showFrame(frameId) {
    const asset = FRAMES[frameId];
    if (!asset) return;
    const incoming = activeImg === frameA ? frameB : frameA;
    if (activeImg) activeImg.classList.remove('active');
    incoming.src = asset.img.src;
    incoming.classList.add('active');
    activeImg = incoming;
    const w = stage.clientWidth || 358;
    stage.style.aspectRatio = 'auto';
    stage.style.height = `${Math.round(Math.min(STAGE_MAX_H, w * (asset.clipH / FRAME_W)))}px`;
  }

  function paintStepUi(index) {
    const step = TIMELINE[index];
    dotsWrap.querySelectorAll('.fv-dot').forEach((d, i) => {
      d.classList.toggle('active', i === index);
      d.classList.toggle('done', i < index);
    });
    countEl.textContent = `${index + 1} / ${TIMELINE.length}`;
    if (step.badge) {
      const b = BADGES[step.badge];
      badgeEl.textContent = b.label;
      badgeEl.className = `fv-badge ${b.cls}`;
      badgeEl.style.display = 'block';
    } else {
      badgeEl.style.display = 'none';
    }
    captionEl.textContent = step.caption || '';
  }

  function jumpToStep(index) {
    const wasPlaying = playing;
    timersClear();
    stepIndex = Math.max(0, Math.min(index, TIMELINE.length - 1));
    pausedElapsed = 0;
    stepStart = 0;
    showFrame(FRAMES[TIMELINE[stepIndex].frame]);
    paintStepUi(stepIndex);
    if (wasPlaying) setPlaying(true);
    else setProgress(0);
  }

  function setPlaying(value) {
    playing = value;
    playBtn.innerHTML = playing ? pauseSvg : playSvg;
    if (playing) playStep();
    else pauseStep();
  }

  function playStep() {
    timersClear();
    const step = TIMELINE[stepIndex];
    showFrame(step.frame);
    paintStepUi(stepIndex);
    const total = totalsFor(step);
    const elapsed = Math.min(total, pausedElapsed);
    stepStart = Date.now() - elapsed;
    const remaining = total - elapsed;

    progressFill.style.transition = 'none';
    setProgress((elapsed / total) * 100);
    void progressFill.offsetWidth;
    progressFill.style.transition = `width ${remaining}ms linear`;
    setProgress(100);

    const target = hotspotXY(step);
    cursorEl.style.opacity = '1';
    if (elapsed < MOVE_MS) {
      glide(cursorPt, target, Math.max(1, MOVE_MS - elapsed));
      cursorPt = target;
    } else {
      cursorEl.style.left = `${target.x}px`;
      cursorEl.style.top = `${target.y}px`;
      cursorPt = target;
    }
    if (step.click) {
      const delay = Math.max(0, MOVE_MS + 40 - elapsed);
      rippleTimer = setTimeout(() => spawnRipple(target.x, target.y), delay);
    }
    if (step.type) {
      const delay = Math.max(0, MOVE_MS + 300 - elapsed);
      typingTimer = setTimeout(() => beginTyping(target.x, target.y, step.type), delay);
    }

    stepTimer = setTimeout(nextStep, remaining);
  }

  function nextStep() {
    pausedElapsed = 0;
    stepStart = 0;
    if (stepIndex + 1 < TIMELINE.length) {
      stepIndex += 1;
      paintStepUi(stepIndex);
      playStep();
      return;
    }
    finishTour();
  }

  function glide(from, to, ms) {
    if (ms <= 0) {
      cursorEl.style.left = `${to.x}px`;
      cursorEl.style.top = `${to.y}px`;
      return;
    }
    const t0 = performance.now();
    const ease = (t) => 1 - Math.pow(1 - t, 3);
    const frame = (now) => {
      const t = Math.min(1, (now - t0) / ms);
      const e = ease(t);
      cursorEl.style.left = `${from.x + (to.x - from.x) * e}px`;
      cursorEl.style.top = `${from.y + (to.y - from.y) * e}px`;
      if (t < 1) moveRaf = requestAnimationFrame(frame);
    };
    moveRaf = requestAnimationFrame(frame);
  }

  function spawnRipple(px, py) {
    const old = stage.querySelector('.fv-ripple');
    if (old) old.remove();
    const ripple = document.createElement('span');
    ripple.className = 'fv-ripple';
    ripple.style.left = `${px}px`;
    ripple.style.top = `${py}px`;
    stage.appendChild(ripple);
    rippleTimer = setTimeout(() => ripple.remove(), 800);
  }

  function beginTyping(px, py, text) {
    if (typingChip) removeTypingChip();
    typingChip = document.createElement('span');
    typingChip.className = 'fv-typing';
    typingChip.style.left = `${px + 8}px`;
    typingChip.style.top = `${py + 16}px`;
    typingChip.textContent = '';
    stage.appendChild(typingChip);
    if (typingTimer) clearInterval(typingTimer);
    let i = 0;
    typingTimer = setInterval(() => {
      i += 3;
      typingChip.textContent = text.slice(0, Math.min(i, text.length));
      if (i >= text.length) {
        clearInterval(typingTimer);
        typingTimer = null;
        typingDoneTimer = setTimeout(() => { typingChip.textContent = '••••·•'; }, 60);
      }
    }, 110);
  }

  function removeTypingChip() {
    if (typingChip) { typingChip.remove(); typingChip = null; }
    if (typingDoneTimer) { clearTimeout(typingDoneTimer); typingDoneTimer = null; }
  }

  function finishTour() {
    playing = false;
    playBtn.innerHTML = playSvg;
    timersClear();
    pausedElapsed = 0;
    progressFill.style.transition = 'none';
    setProgress(100);
    captionEl.textContent = 'Tour finished — the ▶ button in the popup header replays it anytime.';
  }

  function open(source) {
    ensureBuilt();
    trackEvent('feature_video_played', { source: source ? 'header' : 'prompt' });
    stepIndex = 0;
    pausedElapsed = 0;
    stepStart = 0;
    timersClear();
    showFrame(FRAMES['idle']);
    paintStepUi(0);
    modal.style.display = 'flex';
    cursorPt = hotspotXY(TIMELINE[0]);
    cursorEl.style.left = `${cursorPt.x}px`;
    cursorEl.style.top = `${cursorPt.y}px`;
    playing = true;
    playBtn.innerHTML = pauseSvg;
    progressFill.style.transition = 'none';
    setProgress(0);
    playStep();
  }

  function close() {
    if (!built) return;
    timersClear();
    playing = false;
    modal.style.display = 'none';
    playBtn.innerHTML = playSvg;
  }

  function togglePlay() {
    setPlaying(!playing);
  }

  window.PocketResumeFeatureVideo = { open, close };
})();
